### ISSUE TITLE
3-Stage Optimization Code?

### ISSUE THREAD

**Issue by GloryyrolG** [eth-ait/emdb#2]
Hi @kaufManu @eltociear et al.,

Thx for ur great contribution to the field. May I know if you plan to release the annotation script, i.e., 3-stage optimization?

Best,

**Comment by kaufManu** [comment]
Hi @GloryyrolG and apologies for the late reply. We do not plan to release the code at this point. The stage 3 code has been adapted from Vid2avatar, which is available [here](https://github.com/MoyGcc/vid2avatar).
