### ISSUE TITLE
Why does evaluation align at the midpoint of hip joints, not pelvis?

### ISSUE THREAD

**Issue by isarandi** [eth-ait/emdb#3]
Thank you for this great dataset!

While going through the eval code, I noticed that for root-relative MPJPE, the alignment is performed at the midpoint between the left and right hip joints and not at the pelvis joint. Is there any particular reason for this?

https://github.com/eth-ait/emdb/blob/9a4eab677181a3789bda7ba5c36ab8cff797380c/evaluation_metrics.py#L94

Thanks!

**Comment by kaufManu** [comment]
Hi, happy to hear you find the data useful! There is no particular reason - we just decided to follow the AGORA protocol where [they do the same](https://github.com/pixelite1201/agora_evaluation/blob/ed739e0f5496dedb4a2f45f9a45aac4c479adea8/agora_evaluation/calculate_v2v_error.py#L111).
