### ISSUE TITLE
Error in visualize.py about SMPLLayer

### ISSUE THREAD

**Issue by rkomatsu2020** [eth-ait/emdb#5]
I have downloaded SMPL file named SMPL_python_v.1.1.0 from official site and setting the configuration of the path of SMPLX_MODELS.
However I met the error that 
**{my_path}/SMPL_python_v.1.1.0\smpl\SMPL_MALE.pkl does not exist!**
I would like ask that is is correct to download SPML not SPMLX (if the program works on SMPL, how to get the file such as SMPL_MALE.pkl) and how to modify to activate SMPLLayer function.

**Comment by kaufManu** [comment]
The code expects the SMPL-family models to be in a directory structure as required by the [`smplx`](https://github.com/vchoutas/smplx#downloading-the-model) package - even if you are only using the SMPL model, and not SMPL-X or SMPL+H etc. Please follow the instructions [here](https://github.com/vchoutas/smplx?tab=readme-ov-file#downloading-the-model) and [here](https://github.com/vchoutas/smplx?tab=readme-ov-file#smpl-and-smplh-setup) to see how to prepare the SMPL models and make sure your directory structure follows the structure and naming as documented [here](https://github.com/vchoutas/smplx?tab=readme-ov-file#model-loading).
