### ISSUE TITLE
the question about Table 3

### ISSUE THREAD

**Issue by YangChangHee** [eth-ait/emdb#6]
Hello :)
Thank you for your great work.
I have a question, so I'm leaving an issue. In Main Paper Table 3, comparisons between each SOTA are marked with (+-). Could you please clarify what (+-) indicates in the comparison?
Also, I'm curious if Table 3 represents fine-tuning on the EMDB dataset.
Thank you! :)

**Comment by kaufManu** [comment]
Hi, thanks for the questions:
- The +/- signs in Tab. 3 represent standard deviations.
- The numbers in Tab. 3 were obtained without fine-tuning on EMDB.

**Comment by YangChangHee** [comment]
Thank you for your response. 
So, were the models obtained from Tab. 3 trained using 3DPW?

**Comment by kaufManu** [comment]
We use the models provided by the baselines, so it follows the setting of the respective baseline. IIRC, for instance, HybrIK, CLIFF trains on 3DPW, PyMAF doesn't.
Hope that helps!

**Comment by YangChangHee** [comment]
I really appreciate your response!
It helped me a lot.
Thank you :)
issue close.
